import {
  ShoppingBag,
  Utensils,
  Car,
  Home,
  Gamepad2,
  Heart,
  GraduationCap,
  Gift,
  Briefcase,
  Wallet,
  CreditCard,
  PiggyBank,
  TrendingUp,
  HelpCircle,
  Coffee,
  Plane,
  Smartphone,
  Shirt,
  Scissors,
  Baby,
  Pill,
  Dumbbell,
  Music,
  Film,
  Book,
  Wrench,
  Zap,
  Droplets,
  type LucideIcon,
} from 'lucide-react';

const iconMap: Record<string, LucideIcon> = {
  // Expense categories
  food: Utensils,
  餐饮: Utensils,
  coffee: Coffee,
  咖啡: Coffee,
  shopping: ShoppingBag,
  购物: ShoppingBag,
  transport: Car,
  交通: Car,
  travel: Plane,
  旅行: Plane,
  entertainment: Gamepad2,
  娱乐: Gamepad2,
  health: Heart,
  医疗: Heart,
  pill: Pill,
  医药: Pill,
  education: GraduationCap,
  教育: GraduationCap,
  gift: Gift,
  礼物: Gift,
  home: Home,
  居家: Home,
  rent: Home,
  房租: Home,
  phone: Smartphone,
  通讯: Smartphone,
  clothing: Shirt,
  服饰: Shirt,
  beauty: Scissors,
  美容: Scissors,
  baby: Baby,
  母婴: Baby,
  fitness: Dumbbell,
  运动: Dumbbell,
  music: Music,
  音乐: Music,
  movie: Film,
  电影: Film,
  book: Book,
  书籍: Book,
  repair: Wrench,
  维修: Wrench,
  electricity: Zap,
  水电: Zap,
  water: Droplets,
  utilities: Droplets,

  // Income categories
  salary: Briefcase,
  工资: Briefcase,
  bonus: Wallet,
  奖金: Wallet,
  investment: TrendingUp,
  投资: TrendingUp,
  refund: CreditCard,
  退款: CreditCard,
  savings: PiggyBank,
  储蓄: PiggyBank,
};

export function getCategoryIcon(iconName?: string): LucideIcon {
  if (!iconName) return HelpCircle;
  return iconMap[iconName] || iconMap[iconName.toLowerCase()] || HelpCircle;
}
